version: 1.0.{build}
image: Visual Studio 2015


clone_depth: 1


environment:
  matrix:
  #- PlatformToolset: v140
  - PlatformToolset: v120
  # doesn't build c++11 missing, would require boost build cfg - PlatformToolset: v110

platform:
    - x64
    - Win32

configuration:
    #- Release
    - Debug

install:
    - git submodule -q update --init
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd c:\projects\nppPluginManager\
    - mkdir unicodeAppDataPlugins
    - msbuild PluginManager.sln /m /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%"

after_build:
    - cd c:\projects\nppPluginManager\
    - ps: >-
        $nppPluginManagerFileName = "PluginManager.$env:PLATFORM.$env:CONFIGURATION.$env:PLATFORMTOOLSET.dll"

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "x64\Release\PluginManager.dll" -FileName "$nppPluginManagerFileName"
        }

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Debug") {
            Push-AppveyorArtifact "x64\Debug\PluginManager.dll" -FileName "$nppPluginManagerFileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "Release\PluginManager.dll" -FileName "$nppPluginManagerFileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Debug") {
            Push-AppveyorArtifact "Debug\PluginManager.dll" -FileName "$nppPluginManagerFileName"
        }

